[package]
name = "soldier_infra"
version = "0.1.0"
edition = "2024"

[dependencies]
soldier_core = { path = "../soldier_core" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
