[package]
name = "soldier_infra"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
soldier_core = { path = "../soldier_core" }

[dev-dependencies]
serde_json = "1"
